---

- name: Restart firewalld
  become: yes
  service:
    name: firewalld
    state: restarted

- name: Restart ssh
  become: yes
  service:
    name: sshd
    state: restarted

- name: Restart fail2ban
  become: yes
  service:
    name: fail2ban
    state: restarted

...
